// Curated day plans: each starts from the user's picks and adds top-ranked events near them.
window.PRESETS = [
  { id: "sat-uptown", day: "sat", name: "Harlem to Long Island City",
    blurb: "Four of your picks in one sweep: the CCNY campus, Harborview, Weinstein's glass studio and Westbeth. Adds the Spitzer robotics lab next door and the stone carvers, a walk from Harborview. Westbeth's last tour ends the day.",
    stops: ["great-hall-26", "spitzer-26", "harborview-terrace-26", "pellettieri-26", "nikolas-weinstein-26", "westbeth-26"] },
  { id: "sat-queens", day: "sat", name: "Rooftop farm and glass studio",
    blurb: "Starts at Sky Farm and Weinstein in Queens, crosses to the Mechanics' lock collection in Midtown, then a walkable West Side finish: the Hudson River Wetlab, the LILAC and Westbeth.",
    stops: ["sky-farm-26", "nikolas-weinstein-26", "general-society-26", "wetlab-26", "lilac-26", "westbeth-26"] },
  { id: "sat-waterfront", day: "sat", name: "Brooklyn by air and water",
    blurb: "The control tower and baggage tunnels at Floyd Bennett Field, your seltzer factory, the 1938 tanker MARY A. WHALEN, and a last canoe on the Gowanus. Long transit legs: Floyd Bennett to Seltzer is about 1.5 hours by bus and train.",
    stops: ["floyd-bennett-26", "seltzer-26", "mary-whalen-26", "gowanus-canoeing-26"] },
  { id: "sat-garment", day: "sat", name: "Midtown makers",
    blurb: "Harborview first, then the densest cluster of my top picks: the stone-carving academy, a 1931 pleating factory and the Mechanics' locks, before Weinstein in Long Island City and Westbeth.",
    stops: ["harborview-terrace-26", "pleating-26", "pellettieri-26", "general-society-26", "nikolas-weinstein-26", "westbeth-26"] },
  { id: "sat-best", day: "sat", name: "My top-ranked Saturday",
    blurb: "Ignores your list and runs my #2, #3 and #4: Floyd Bennett Field, the Navy Yard labs and the MARY A. WHALEN. Few stops, because each one is big and they're far apart.",
    stops: ["floyd-bennett-26", "navy-yard-26", "mary-whalen-26"] },

  { id: "sun-green", day: "sun", name: "Rooftops, canoes and stars",
    blurb: "Four of your picks: Brooklyn Grange, the Gowanus canoes, Kingsland's rooftop meadows and the telescopes in Elmhurst. Adds Powerhouse Arts (#7), a short walk from the canoe dock.",
    stops: ["brooklyn-grange-26", "gowanus-canoeing-26", "powerhouse-26", "kingsland-wildflowers-26", "aaa-elmhurst-26"] },
  { id: "sun-uptown", day: "sun", name: "Fire tower and wildflower roofs",
    blurb: "Sky Farm, then up to the hidden Lotus Garden and the Mount Morris fire watchtower (get there early for the line), then Kingsland's rooftop meadows in Greenpoint and stargazing. The Noo Arts tour doesn't fit: its last slot starts 2:30 and Mount Morris runs until then.",
    stops: ["sky-farm-26", "lotus-garden-26", "mount-morris-26", "kingsland-wildflowers-26", "aaa-elmhurst-26"] },
  { id: "sun-sunsetpark", day: "sun", name: "Sunset Park makers",
    blurb: "Brooklyn Grange, then the MakerSpace forge and Cass Gilbert's Army Terminal atrium next door, live glassblowing at Brooklyn Glass, a canoe on the Gowanus, and stargazing.",
    stops: ["brooklyn-grange-26", "makerspace-26", "bat-26", "brooklyn-glass-26", "gowanus-canoeing-26", "aaa-elmhurst-26"] },
  { id: "sun-outer", day: "sun", name: "Far Brooklyn",
    blurb: "Built around Ecology Park, the hardest of your picks to reach. Brooklyn Grange first, then the restored natural area at Paerdegat Basin (about 1.5 hours by train and bus), the New York Sign Museum (#12), and stargazing.",
    stops: ["brooklyn-grange-26", "ecology-park-26", "noble-26", "aaa-elmhurst-26"] },
  { id: "sun-westside", day: "sun", name: "Manhattan Sunday",
    blurb: "Lotus Garden, a Rockefeller Center roof garden, the Mount Morris watchtower, then Westbeth and the LILAC downtown before heading to Queens for the telescopes.",
    stops: ["lotus-garden-26", "620-loft-26", "mount-morris-26", "westbeth-26", "lilac-26", "aaa-elmhurst-26"] },
];
